### ISSUE TITLE
Settings page BE functionality + FE polishing

### ISSUE THREAD

**Issue by Fezzzi** [Fezzzi/Household-Chores#40]
- [x] Add notifications model
 - [x] Implement functionality for the whole FE settings page
 - [x] ~Denote a way of displaying additional information about the option (such as what will happen when user clicks block button / information about certain notification settings / visibility / etc..)~ separated to #59 
 - [x] Allow user to remove his account - Should be pretty straightforward, just check db cascades correcly (no need to clean fs as cron should do that sooner or later anyway) - done on FE, BE will be done as part of #13 
 - [x] Refactor input components and forms to use hooks
 - [x] ~Refacstor existing BE form handling to stop using `{ value: any, valid: bool }` shape of input values~ resolved as part of #19 
 - [x] ~Refactor BE to stop using ternary values and use some shapes instead~ resolved as part of #19
