### ISSUE TITLE
Pending fixes

### ISSUE THREAD

**Issue by Fezzzi** [Fezzzi/Household-Chores#63]
### FIXES
 - [x] ~Polluted localstorage causes app to crash~ resolved as part of #81 
 - [ ] Add throbber to avoid 'flicking'
 - [ ] Resolve empty notifications on Auth screen
 - [ ] Create directory for default images
 - [ ] Move default user and household images here
 - [ ] Navbar crashes when user has no 
 - [ ] Make newly created users and households created with default image use these images
 - ~Make household selecting on main page modify route~
 - [x] ~Fix BE to actually return 4xx and 5xx response codes on errors and modify Fe accordingly~- resolved as part of #69 
 - [x] ~Dialog Settings page does not refresh state correctly~ - resolved as part of #69 
 - [x] ~Household settings > back > Household settings causes page to break~ resolved somewhere
 - [x] ~User state doesn't update after successful login (signup probably as well)~ resolved as part of #81
 - [x] ~Connection request message won't show after sending until refreshed~ - resolved as part of #69 
 - [ ] Households > ignoring invitation doesn't refresh the page / update state
 - [ ] Resolve remaining pending todos if any
 - [ ] My Households won't show in Households tab until re-render happens, either by a click or mouse-over
 - [ ] Make some request pass ids of updated entities (e.g. `householdId`) via route (e.g. `.../{id}/...`) instead of merged withing body's `inputs`
